#!/usr/bin/env node

var arg = process.argv[2];
if (arg === '-v' || arg === '--version') {
	console.log(require('./package.json').version)
}
else {
	require('babel-core/register');
	require('./src/scaffold');
}
